SELECT TENANT_ID,BANKNAME FROM dbo.OSUSR_K0H_BANKTENANT_SERVICESCONFIG 
select * from dbo.OSUSR_K0H_BANKTENANT_ACCOUNTLINKINGCONFIG

--UPDATE  dbo.OSUSR_K0H_BANKTENANT_ACCOUNTLINKINGCONFIG
--SET	CLIENTNAME = 'falmouth',
--	CLIENTID   = '6a1f3a04ab8f7b000d2dee63',
--	SECRET     = 'e2592f0f58005fa4af1a1491fe24ac',
--	URL        = 'https://sandbox.plaid.com'
--WHERE TENANT_ID = 137 and ID =5