--SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_SERVICESCONFIG

DECLARE
@TENANT_ID        AS VARCHAR(250) = '197',
@USERNAME_LIKE     AS VARCHAR(250) = '%@roca.dev%'

SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_SERVICESCONFIG where TENANT_ID = @TENANT_ID
SELECT * FROM dbo.ossys_User WHERE TENANT_ID = @TENANT_ID and  username like @USERNAME_LIKE
--The conflict occurred in database "outsystems_savana_demo", table "dbo.OSUSR_K0H_BANKTENANT_USER_ROLES", column 'USER_ID'.
SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_USER_ROLES WHERE USER_ID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )ORDER BY 3
--DELETE FROM dbo.OSUSR_K0H_BANKTENANT_USER_ROLES WHERE USER_ID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE ) 

--The conflict occurred in database "outsystems_savana_demo", table "dbo.OSUSR_K0H_BANKTENANT_USER_CREATEDBY", column 'USERID'.
SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_USER_CREATEDBY WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )ORDER BY 3
--DELETE FROM dbo.OSUSR_K0H_BANKTENANT_USER_CREATEDBY WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )

SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_USER_CREATEDBY WHERE CREATEDBY IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )ORDER BY 3
--DELETE FROM dbo.OSUSR_K0H_BANKTENANT_USER_CREATEDBY WHERE CREATEDBY IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )

--The conflict occurred in database "outsystems_savana_demo", table "dbo.OSUSR_K0H_USEREXTENDED", column 'USERID'.
SELECT * FROM dbo.OSUSR_K0H_USEREXTENDED WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )ORDER BY USERID
--DELETE FROM dbo.OSUSR_K0H_USEREXTENDED WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )

--The conflict occurred in database "outsystems_savana_demo", table "dbo.OSUSR_K0H_BANKTENANT_USERS", column 'USERID'.
SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_USERS WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )ORDER BY USERID
--DELETE FROM dbo.OSUSR_K0H_BANKTENANT_USERS WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )

--The conflict occurred in database "outsystems_savana_demo", table "dbo.OSUSR_K0H_BANKTENANT_USER_AUDIT", column 'MODIFIEDBYUSERID'.
SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_USER_AUDIT WHERE MODIFIEDBYUSERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )ORDER BY MODIFIEDBYUSERID
--DELETE FROM dbo.OSUSR_K0H_BANKTENANT_USER_AUDIT WHERE MODIFIEDBYUSERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )

SELECT * FROM dbo.OSUSR_K0H_BANKTENANT_USER_AUDIT WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )ORDER BY MODIFIEDBYUSERID
--DELETE FROM dbo.OSUSR_K0H_BANKTENANT_USER_AUDIT WHERE USERID IN (SELECT ID FROM dbo.ossys_User WITH (NOLOCK) WHERE TENANT_ID = @TENANT_ID  and  username like @USERNAME_LIKE )

--DELETE FROM dbo.ossys_User WHERE TENANT_ID = 222 and  username like @USERNAME_LIKE 